### ISSUE TITLE
How to track down the root cause of a ClassNotFoundException

### ISSUE THREAD

**Issue by gtaylor** [realityforge/gelf4j#11]
Hello,

I am attempting to set up gelf4j with datastax-agent, which is a daemon that the commercial version of Cassandra (DataStax Enterprise) uses to manage nodes in a cluster. It uses log4j 1.2.17 and Java 8.

Here is the command my startup script runs:

```
/usr/lib/jvm/java-8-oracle/jre/bin/java -Xmx128M -Djclouds.mpu.parts.magnitude=100000 -Djclouds.mpu.parts.size=16777216 -cp /usr/share/datastax-agent/lib/json-simple-1.1.jar -cp /usr/share/datastax-agent/lib/getopt4j-1.1.jar -cp /usr/share/datastax-agent/lib/gelf4j-1.9.jar -Dopscenter.ssl.trustStore=/var/lib/datastax-agent/ssl/agentKeyStore -Dopscenter.ssl.keyStore=/var/lib/datastax-agent/ssl/agentKeyStore -Dopscenter.ssl.keyStorePassword=opscenter -Dagent-pidfile=/var/run/datastax-agent/datastax-agent.pid -Dlog4j.configuration=file:/etc/datastax-agent/log4j.properties -Djava.security.auth.login.config=/etc/datastax-agent/kerberos.config -jar /usr/share/datastax-agent/datastax-agent-5.1.3-standalone.jar /var/lib/datastax-agent/conf/address.yaml
```

Here is the error I'm seeing:
```
log4j:ERROR Could not instantiate class [gelf4j.log4j.GelfAppender].
java.lang.ClassNotFoundException: gelf4j.log4j.GelfAppender
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.log4j.helpers.Loader.loadClass(Loader.java:198)
	at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:327)
	at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:124)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:785)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:66)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at com.datastax.driver.core.Cluster.<clinit>(Cluster.java:65)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at clojurewerkz.cassaforte.client__init.__init0(Unknown Source)
	at clojurewerkz.cassaforte.client__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.loadClassForName(RT.java:2098)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5336)
	at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
	at clojure.core$load_lib.doInvoke(core.clj:5374)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5413)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$require.doInvoke(core.clj:5496)
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at opsagent.cassandra$loading__4910__auto__.invoke(cassandra.clj:1)
	at opsagent.cassandra__init.load(Unknown Source)
	at opsagent.cassandra__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.loadClassForName(RT.java:2098)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5336)
	at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
	at clojure.core$load_lib.doInvoke(core.clj:5374)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5413)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$require.doInvoke(core.clj:5496)
	at clojure.lang.RestFn.invoke(RestFn.java:2793)
	at opsagent.opsagent$loading__4910__auto__.invoke(opsagent.clj:1)
	at opsagent.opsagent__init.load(Unknown Source)
	at opsagent.opsagent__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.loadClassForName(RT.java:2098)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:415)
	at opsagent.opsagent.<clinit>(Unknown Source)
log4j:ERROR Could not instantiate appender named "gelf".
 INFO [main] 2015-07-07 19:13:09,190 Loading conf files: /var/lib/datastax-agent/conf/address.yaml
  INFO [main] 2015-07-07 19:13:09,234 Java vendor/version: Java HotSpot(TM) 64-Bit Server VM/1.8.0_45
  INFO [main] 2015-07-07 19:13:09,235 DataStax Agent version: 5.1.3
```

The top-level jar file is `/usr/share/datastax-agent/datastax-agent-5.1.3-standalone.jar`. I created a `/usr/share/datastax-agent/lib/` directory to stick new dependencies under. That datastax-agent jar has a bunch of other stuff wrapped up within, so I resorted to manually plucking dependencies from maven central. See my command string above for the -cp entries for the new jar files.

Consequently, here is what my /lib directory looks like:

* /usr/share/datastax-agent/lib/json-simple-1.1.jar
* /usr/share/datastax-agent/lib/getopt4j-1.1.jar
* /usr/share/datastax-agent/lib/gelf4j-1.9.jar

I'm a Java newbie, so any help with figuring out how to diagnose this would be awesome. If I can get this figured out, I'd love to blog about using gelf4j with Cassandra, since they would make a great pair.

**Comment by gtaylor** [comment]
Looks like -cp and -jar are mutually exclusive. I got this working by passing in -cp and replacing the -jar + args with the entrypoint class.
